id: IE0E448C2
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:15:38.795843
last_modified: 2023-02-08 15:15:38.795933
source_metadata:
  title: 'PP: Prajñāpāramitāhṛdaya'
  language: zh
bases:
  025D:
    base_file: 025D.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
